### PR TITLE
feat(angular): Add getUser to Angular

### LINKED ISSUE #107: getUser should return info from the `/userinfo` endpoint or decode `idToken`
if `accessToken` -> request `/userinfo` endpoint
if !`accessToken` -> decode `idToken` for claims

### PR DESCRIPTION
**Pull request by cmckni3**
Close #107

### CODE REVIEW

**Comment by cmckni3** [comment]
We can talk here about my comment on #107. I am willing to help out with this code since I need it ASAP.

**Comment by jmelberg-okta** [comment]
Hey @cmckni3! Thanks for all your work on the last couple of PRs. We're going to take a look at these as soon as we can.

Re: #107 
There are three primary use cases we need to support for `getUser`:
1. Requesting `id_token token` (default)
    - If there is an `accessToken` stored, make a call to the `/userinfo` endpoint to return all available user information based on the `scopes` requested.
2. Requesting `id_token`
    - `getUser` should decode the token and return the payload of the `jwt`
3. Requesting `token`
    - Same as 1.

As you mentioned, the claims in the `idToken` may become stale/expired. Common practice is to keep a short `idToken` expiration time - then rely on the underlying library [`AuthJS`](https://github.com/okta/okta-auth-js) to handle refreshing the tokens when needed.

**Comment by cmckni3** [comment]
That makes sense @jmelberg-okta according to the Oauth specification. I mostly struggle with following the AuthJS code since none of the documentation is available in TypeScript.

**Comment by cmckni3** [comment]
I worked around this in my current application by calling `loginRedirect`.

**Pull request closed without merging**
