### PR TITLE
okta-vue - expose AuthJS to vue

### LINKED ISSUE #19: okta-react: Make Auth.js service available outside of React components
Hi,
It would be useful if you made the methods in the Auth class available without having to use the withAuth HOC.

This is useful when you need to use the access token outside of React. For example when using [Apollo Client](http://dev.apollodata.com/react/auth.html#Header).

Thanks

### PR DESCRIPTION
**Pull request by gaastonsr**
This one is closely related to #19. It's the equivalent of #97 but for Vue.

I couldn't run the tests though. I would appreciate it if somebody could verify it works or could guide me on how to do it.

Fixes #19.

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
Hey @gaastonsr - I'm a little unsure about this change. While exposing this makes sense for flows that `okta-vue` currently doesn't support - it also deeply couples `okta-vue` to `okta-auth-js`.

What flows do we not support that you're using `okta-auth-js` for currently?

**Comment by gaastonsr** [comment]
Right now we need to be inside a component to have access auth object. We would like to be able to access it from Vuex directly.

**Comment by kevlened** [comment]
@gaastonsr #19 was resolved in #97 by creating an instance of `Auth` and passing it in. That solution makes sense here too, because it gets you access to the `Auth` methods and addresses @jmelberg-okta's concern of being coupled to `okta-auth-js`.

**Comment by kevlened** [comment]
@gaastonsr Turns out that a similar solution won't work with the Vue implementation currently, but you can work around it by using the Vue global.

```javascript
Vue.use(Auth, {
  issuer: 'yours',
  client_id: 'yours',
  redirect_uri: 'yours',
  scope: 'openid',
});

Vue.prototype.$auth // Do what you need
```

**Pull request closed without merging**
