### PR TITLE
fix[okta-angular]: Adds canActivateChild to OktaAuthGuard.

### PR DESCRIPTION
**Pull request by jraadt**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #424 

## What is the new behavior?
Adds canActivateChild to OktaAuthGuard.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jraadt** [comment]
This is a very small, but very helpful PR for Angular developers that is needed guard child routes. Is there anything I can do to help get this pushed through?

**Comment by jraadt** [comment]
I'm willing to rebase this and resolve conflicts if PRs are welcome, but at this point I'm going to devote my energy to fixing the bugs and adding features in my own fork.

**Comment by mraible** [comment]
I think it's a worthwhile addition. What do you think @aarongranick-okta?

**Comment by aarongranick-okta** [comment]
@jraadt Thanks for the submission. It seems very straightforward. I think we should be able to include this in our next release.

**Comment by aarongranick-okta** [comment]
@jraadt Have you signed our CLA? https://developer.okta.com/cla

**Comment by jraadt** [comment]
@aarongranick-okta I'm unsure if I had signed a CLA so I just submitted a new one. I'll work to rebase my changes. Appreciate you all!

**Comment by jraadt** [comment]
Looks like you guys just did this in #776 ?

**Comment by jraadt** [comment]
This is now in okta-angular 3.0.

**Pull request closed without merging**
