### PR TITLE
Add support for render prop in SecureRoute

### PR DESCRIPTION
**Pull request by tonywuhl**
Support a render prop similar to how Route works

This relates to: https://github.com/okta/okta-oidc-js/issues/78

### CODE REVIEW

**Comment by lboyette-okta** [comment]
Hi @tonywuhl! Thanks for your pull request.

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign our Contributor License Agreement (CLA). 

Please visit developer.okta.com/cla to review, and email a signed copy to cla@okta.com.

Then, reply here (“Signed”) so we can proceed. Thanks!

**Comment by tonywuhl** [comment]
Signed

**Comment by robertjd** [comment]
Thanks @tonywuhl ! This looks great and I verified functionality.  @lboyette-okta anything else you want to look at?

**Comment by lboyette-okta** [comment]
Nope, lgtm. 🚢

**Pull request merged**
