### PR TITLE
feat[okta-angular]: Basic support for authorization code flow

### PR DESCRIPTION
**Pull request by eduardomourar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
It is not possible to use the authorization code flow with angular library.

Issue Number: #187 

## What is the new behavior?
We are able to use the authorization code flow now that we have update to new version of [okta-auth-js](https://github.com/okta/okta-auth-js#pkce-oauth-20-flow).

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks @eduardomourar !  We have plans to work on this soon, so I'll bump @aarongranick-okta to take a look.  I notice that the callback URL is changing, so we need to make sure we are making a consistent decision on our side, across all of these framework libraries.

**Comment by eduardomourar** [comment]
I have already tried this in my test environment and it is working as expected, so I can be your beta tester for angular.

**Comment by aarongranick-okta** [comment]
@eduardomourar looks pretty good, I think we may be able to use a lot of this. One subtle detail: `grantType` option should be set in the OktaAuth constructor so that token auto-renew will also use PKCE flow

**Comment by eduardomourar** [comment]
@aarongranick-okta, I have made the changes to configuration validation as mentioned

**Pull request closed without merging**
