### PR TITLE
fix(okta-config): Expose OktaConfig

### PR DESCRIPTION
**Pull request by cmckni3**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
Hi @cmckni3 - Sorry for my delayed response.

In general, I think this is a valuable change and am happy to merge this in. Before doing so, can you add tests to assert that the `OktaConfig` properties can be read?

**Comment by cmckni3** [comment]
@jmelberg-okta I don't follow. You want a test to make sure `OktaConfig` is exported correctly?

**Comment by jmelberg-okta** [comment]
Yep - more or less. Something similar to what we're already doing with the [`getOktaConfig`](https://github.com/okta/okta-oidc-js/blob/5862e320547ef5dd24ac5717480514f71f72bab3/packages/okta-angular/test/e2e/harness/src/app/app.component.spec.ts#L71-L78) method.

**Comment by cmckni3** [comment]
I updated the tests to import `OktaConfig` in the App module and App component spec.

Let me know if this isn't sufficient. I don't see a reason to have a duplicate test when TypeScript will check the interface for us when compiling the tests.

**Comment by cmckni3** [comment]
Closing for now. Feel free to reopen.

**Pull request closed without merging**
