### PR TITLE
feat(context): migrate to new context api and use hooks

### LINKED ISSUE #428: migrate to new react context api
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

It uses the old context api that is deprecated

## Expected behavior

It should use the new context api

## Environment

- Package Version: 1.2.0
- Browser: chrome
- OS: mac
- Node version (`node -v`): 10.15.0
- Other:

### LINKED ISSUE #429: Provide hooks api
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

It does not have hooks api

## Expected behavior

It should provide hooks api

`useAuth` for instance

## Environment

- Package Version: 1.2.0
- Browser: chrome
- OS: mac
- Node version (`node -v`): 10.15.0
- Other:

### PR DESCRIPTION
**Pull request by sibelius**
- migrate to React.createContext api, fix #428
- provide useOkta hook api, fix #429

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

We need at least react 16.8.0 to make this work

### CODE REVIEW

**Comment by sibelius** [comment]
CLA is signed

**Comment by wbeard** [comment]
Would love to see this PR land!

**Comment by swiftone** [comment]
@wbeard You aren't alone - just waiting for the go-ahead.  This will bump us a major version since it ups the React version requirement, so we try to collect "breaking" features together.  This is certainly not forgotten though.  (And your comments and thumbs up do matter!)

**Comment by pete-redmond-cko** [comment]
@swiftone any update on this PR getting merged?

**Comment by swiftone** [comment]
@pete-redmond-cko No real update - it's slated for consideration in our next major version update.  While those who have expressed an interest are very interested (and we're aware of how quickly hooks are reshaping the React landscape) we've not had a surge in customer numbers looking for this feature, so other areas have been higher priority.  

That said, this is definitely not off our radar and definitely not in the "nice to have but not happening" camp - it's just behind some other issues.

**Comment by wbeard** [comment]
@swiftone While this implementation is destructive, it's possible to make this an additive change. Would an additive change expedite the release?

**Comment by swiftone** [comment]
@wbeard asks "Would an additive change expedite the release?"

That's a great question.  As a programming geek, I'd love to SEE the additive version (I'm a big React fan and hooks are exciting to me), and there's a chance an additive version improves the speed of getting everything in, but there's also a chance that we'd favor doing things one obvious way (along with the reduced maintenance effort involved) so I don't want to promise anything more than my personal interest.

Either way though, it's not likely to get you the change in the library at the speed you (and I) would hope for.  This is because of two parts: 
- We (Okta) have to run through tests and scenarios to make sure the change to use Hooks isn't just working at the moment, but is also in line with any upcoming plans - it has to be something we can and want to maintain rather than quickly doing a dramatic change in implementation in the following version.   A constantly shifting API for our libraries is arguably worse for our customers than one that lags a bit behind the newest practices.  As with so much in programming, the actual coding is often the smaller part.  :( 
- The main obstacle to doing the above work isn't this PR, it's the demand for Hooks from our customers vs the other places we can add value for our customers.  There will always be more work to do, so we'll always be prioritizing some work over other work, even when all the work is particularly worthwhile.  

Now, that said, this PR exists (a good PR definitely helps priority over just a request) and has gotten some 👍 - if it gets more, priorities can further shift.  My team's PM is active here on GH and watches for such things in addition to the other ways the customers give us feedback, and I and the other JS devs at Okta likewise regularly report the levels of interest.  

Absent that though, all I can say is that this is high on our backlog and will be implemented at some point.  I know that's not the most satisfying of answers, sorry.

**Comment by sibelius** [comment]
the new React Context was introduce on 16.3.0
The hooks api needs 16.8.0

Some libs ships this in a separate file, where they test if the react version supports hooks

**Comment by daniloab** [comment]
I would like to see this pr running

**Comment by omarchehab98** [comment]
I suggest naming the hook `useAuth` to be consistent with `withAuth`

**Comment by tobysteward** [comment]
Any update on this being merged?

**Comment by ssteuteville** [comment]
+1 on this..

I wonder if a PR that switched from legacy context api to the new context api and didn't include any hooks work might get merged faster? Seems like it would be easier to do without any compatibility issues.

That would make it easy for your users to simply use `useContext` (or create wrappers around the context).

**Comment by sibelius** [comment]
can we get this merge this?

this is also needed for Strict Mode support

https://reactjs.org/docs/strict-mode.html

so we can run latest React features like concurrent mode

**Comment by ssteuteville** [comment]
Always warnings because of legacy context. Kind of annoying that a PR exists that fix this yet I'm still stuck dependent on deprecated react features.

**Comment by sibelius** [comment]
bump

**Pull request closed without merging**
