### PR TITLE
Adds support for custom jwks URI when it cannot be constructed from issuer URI

### PR DESCRIPTION
**Pull request by vtajzich**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
JWKS URI is based on Issuer URI by appending '/v1/keys'.

Issue Number: N/A

## What is the new behavior?
JWKS URI can be constructed either by appending '/v1/keys' to Issuer URI or it could be provided in options in 'jwksUri' field.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Review by rudovjan — APPROVED** [review]

**Comment by rudovjan** [comment]
Should solve https://github.com/okta/okta-oidc-js/issues/489

**Comment by dollysingh3192** [comment]
Hi @rudovjan / @denysoblohin-okta /  okta-oidc-js Team,

I am using  [jwt-verifier](https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier) on the backend which internally uses Okta-oidc-js monorepo.

I am facing an issue for which this PR has been raised for. I searched the open [Pull Request](https://github.com/okta/okta-oidc-js/pulls) section of this repository and found two relative fixes that have been reported [here](https://github.com/okta/okta-oidc-js/pull/708) and [here](https://github.com/okta/okta-oidc-js/pull/978) 

I also checked the commits of this PR and are perfectly suited as per needs. I request you to please take some actions on it as we have a production release of our in-house SPA in upcoming months.  

Please let me know, as I am also open to contribute in this PR, if anything is pending. 

Thanks in advance!

**Comment by dollysingh3192** [comment]
Hey @vtajzich,

If you give me permission of the forked Repository and add me as a collaborator.  I will raise an MR for pending items.

Thanks!

**Comment by dollysingh3192** [comment]
Hey @denysoblohin-okta ,

I am in real hurry to get this MR merged and since I didn't get any response from @vtajzich 
to give me permission or add as a collaborator of the forked repository where this code has been fixed. Could you please guide me an alternative way ?

**Comment by dollysingh3192** [comment]
Hi @rudovjan / @denysoblohin-okta / okta-oidc-js Team,

I am eagerly waiting for your response.

**Comment by dollysingh3192** [comment]
@denysoblohin-okta /  @rudovjan  / okta-oidc-js Team,,

Conflicts have been resolved. Please review.

**Comment by dollysingh3192** [comment]
Hey Everyone,

As I said earlier we have an upcoming release in few months and I really wanna test this functionality on production.  If you guys could give any tentative date on this PR getting merged would be really very helpful.

Thanks in advance.

**Review by aarongranick-okta — APPROVED** [review]

**Comment by denysoblohin-okta** [comment]
The feature is included in 2.3.0 release

**Pull request closed without merging**
