### PR TITLE
fix(di): Move dependency injection provide to top of providers

### PR DESCRIPTION
**Pull request by cmckni3**
References #176

### CODE REVIEW

**Comment by cmckni3** [comment]
Going to remove the validations in the constructor in a separate PR. Rely on TypeScript for the checks.

**Comment by cmckni3** [comment]
Bump

**Comment by jmelberg-okta** [comment]
@robertjd - This was something you were investigating, correct?

**Comment by cmckni3** [comment]
Closing for now. Feel free to reopen.

**Pull request closed without merging**
