### PR TITLE
Update to okta-oidc-android v1.0.5 to fix Android 10 issue

### PR DESCRIPTION
**Pull request by rbright**
## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [X] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the new behavior?
Updates to [okta-oidc-android v1.0.5](https://github.com/okta/okta-oidc-android/releases/tag/1.0.5) to fix a [blocking issue on Android 10](https://github.com/okta/okta-oidc-android/issues/113).

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by rbright** [comment]
@IldarAbdullin-okta I see that updating to the latest version triggers some failures in the integration test suite. Are you or someone within Okta able to determine the incompatibility that seems to be introduced in versions since v1.0.2?

**Comment by IldarAbdullin-okta** [comment]
@rbright, Do you mean failures in Travis? These failures are not related to your change. There are some issues with test account. Let us re-run the job

**Comment by rbright** [comment]
Oh, perfect.

**Comment by FeiChen-okta** [comment]
This should be closed. A update to 1.0.8 is merged.

**Comment by robertjd** [comment]
@rbright The latest version of this library, 1.2.3, is now on NPM, which contains the change to upgrade the Android SDK to version 1.0.8

**Pull request closed without merging**
